// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACXFFDHiu-mqRM2vsVAhJh7_Fj91AHTDw',
    appId: '1:866528238638:web:2a0366148f82b1b7f6d3bf',
    messagingSenderId: '866528238638',
    projectId: 'event-countdown-8368f',
    authDomain: 'event-countdown-8368f.firebaseapp.com',
    storageBucket: 'event-countdown-8368f.firebasestorage.app',
    measurementId: 'G-XV34E4KCW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAitQUOu_7Jvp9ZFrOU_h6zfJ5JhSNJhKU',
    appId: '1:866528238638:android:128dc02ffb8b785bf6d3bf',
    messagingSenderId: '866528238638',
    projectId: 'event-countdown-8368f',
    storageBucket: 'event-countdown-8368f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTYgtxCsR8Ze4OsHwEmBqa7Pizz2E0rwk',
    appId: '1:866528238638:ios:8eebc5cd05f878e6f6d3bf',
    messagingSenderId: '866528238638',
    projectId: 'event-countdown-8368f',
    storageBucket: 'event-countdown-8368f.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTYgtxCsR8Ze4OsHwEmBqa7Pizz2E0rwk',
    appId: '1:866528238638:ios:8eebc5cd05f878e6f6d3bf',
    messagingSenderId: '866528238638',
    projectId: 'event-countdown-8368f',
    storageBucket: 'event-countdown-8368f.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACXFFDHiu-mqRM2vsVAhJh7_Fj91AHTDw',
    appId: '1:866528238638:web:854adc7080e1f407f6d3bf',
    messagingSenderId: '866528238638',
    projectId: 'event-countdown-8368f',
    authDomain: 'event-countdown-8368f.firebaseapp.com',
    storageBucket: 'event-countdown-8368f.firebasestorage.app',
    measurementId: 'G-RKT152Z4P5',
  );
}
